/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './App.tsx',
    './index.tsx',
    './index.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Material Design 3 — Dark Blue Night palette
        'background':                '#0b1326',
        'surface':                   '#0b1326',
        'surface-dim':               '#0b1326',
        'surface-bright':            '#31394d',
        'surface-container-lowest':  '#060e20',
        'surface-container-low':     '#131b2e',
        'surface-container':         '#171f33',
        'surface-container-high':    '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant':           '#2d3449',
        'surface-tint':              '#89ceff',
        'inverse-surface':           '#dae2fd',
        'inverse-on-surface':        '#283044',
        // Primary — sky blue
        'primary':                   '#89ceff',
        'on-primary':                '#00344d',
        'primary-container':         '#0ea5e9',
        'on-primary-container':      '#003751',
        'primary-fixed':             '#c9e6ff',
        'primary-fixed-dim':         '#89ceff',
        'on-primary-fixed':          '#001e2f',
        'on-primary-fixed-variant':  '#004c6e',
        'inverse-primary':           '#006591',
        // Secondary — lime green (padel ball)
        'secondary':                 '#9ddf2e',
        'on-secondary':              '#213600',
        'secondary-container':       '#83c300',
        'on-secondary-container':    '#304b00',
        'secondary-fixed':           '#b2f746',
        'secondary-fixed-dim':       '#98da27',
        'on-secondary-fixed':        '#121f00',
        'on-secondary-fixed-variant':'#334f00',
        // Tertiary — sky tint
        'tertiary':                  '#7bd0ff',
        'on-tertiary':               '#00354a',
        'tertiary-container':        '#00a7e0',
        'on-tertiary-container':     '#00384e',
        'tertiary-fixed':            '#c4e7ff',
        'tertiary-fixed-dim':        '#7bd0ff',
        'on-tertiary-fixed':         '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        // Surfaces text
        'on-background':             '#dae2fd',
        'on-surface':                '#dae2fd',
        'on-surface-variant':        '#bec8d2',
        'outline':                   '#88929b',
        'outline-variant':           '#3e4850',
        // Error
        'error':                     '#ffb4ab',
        'on-error':                  '#690005',
        'error-container':           '#93000a',
        'on-error-container':        '#ffdad6',
        // Legacy aliases (backward compat)
        'brand-primary':             '#89ceff',
        'brand-secondary':           '#9ddf2e',
      },
      fontFamily: {
        'manrope': ['Manrope', 'system-ui', 'sans-serif'],
        'display-lg':  ['Manrope', 'system-ui', 'sans-serif'],
        'headline-lg': ['Manrope', 'system-ui', 'sans-serif'],
        'headline-md': ['Manrope', 'system-ui', 'sans-serif'],
        'body-lg':     ['Manrope', 'system-ui', 'sans-serif'],
        'body-md':     ['Manrope', 'system-ui', 'sans-serif'],
        'label-bold':  ['Manrope', 'system-ui', 'sans-serif'],
        'stats-num':   ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg':  ['48px', { lineHeight: '1.1',  letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2',  letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3',  fontWeight: '700' }],
        'body-lg':     ['18px', { lineHeight: '1.6',  fontWeight: '400' }],
        'body-md':     ['16px', { lineHeight: '1.5',  fontWeight: '400' }],
        'label-bold':  ['14px', { lineHeight: '1.2',  fontWeight: '700' }],
        'stats-num':   ['20px', { lineHeight: '1',    letterSpacing: '0.05em', fontWeight: '800' }],
      },
      spacing: {
        'unit':                       '4px',
        'stack-sm':                   '8px',
        'stack-md':                   '16px',
        'stack-lg':                   '32px',
        'gutter':                     '20px',
        'container-padding-mobile':   '16px',
        'container-padding-desktop':  '40px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        'lg':    '0.5rem',
        'xl':    '0.75rem',
        'full':  '9999px',
      },
    }
  },
  plugins: [],
}
